### ISSUE TITLE
Main Features TODO

### ISSUE THREAD

**Issue by SciencyBagel** [SciencyBagel/personal-website#1]
### Here are the main features I would like to see on this website.

- [ ] Use of Database Management System
- [ ] More Personalized Styling
- [ ] Blog Creation Interface
